#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade
#

import wx




class Frame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("Slider Test")

        self.panel = wx.Panel(self, wx.ID_ANY)

        vSizer = wx.BoxSizer(wx.VERTICAL)

        vLabel = wx.StaticText(self.panel, wx.ID_ANY, "Slider(in vertical sizer)")
        vSizer.Add(vLabel, 0, 0, 0)

        self.vSlider = wx.Slider(self.panel, wx.ID_ANY, 0, 0, 100)
        vSizer.Add(self.vSlider, 0, wx.EXPAND, 0)

        hSizer = wx.BoxSizer(wx.HORIZONTAL)
        vSizer.Add(hSizer, 1, wx.EXPAND, 0)

        hLabel = wx.StaticText(self.panel, wx.ID_ANY, "Slider(in horizontal sizer)")
        hSizer.Add(hLabel, 0, 0, 0)

        self.hSlider = wx.Slider(self.panel, wx.ID_ANY, 0, 0, 100)
        hSizer.Add(self.hSlider, 0, wx.EXPAND, 0)

        self.panel.SetSizer(vSizer)

        self.Layout()


class App(wx.App):
    def OnInit(self):
        self.frame = Frame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

if __name__ == "__main__":
    app = App(0)
    app.MainLoop()
